#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libffi-soname6
Version  : 3.2.1
Release  : 35
URL      : https://github.com/libffi/libffi/archive/v3.2.1/libffi-3.2.1.tar.gz
Source0  : https://github.com/libffi/libffi/archive/v3.2.1/libffi-3.2.1.tar.gz
Summary  : Library supporting Foreign Function Interfaces
Group    : Development/Tools
License  : MIT
Requires: compat-libffi-soname6-lib = %{version}-%{release}
Requires: compat-libffi-soname6-license = %{version}-%{release}
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : tcl
BuildRequires : texinfo

%description
Status
======
libffi-3.2.1 was released on November 12, 2014.  Check the libffi web
page for updates: <URL:http://sourceware.org/libffi/>.

%package lib
Summary: lib components for the compat-libffi-soname6 package.
Group: Libraries
Requires: compat-libffi-soname6-license = %{version}-%{release}

%description lib
lib components for the compat-libffi-soname6 package.


%package license
Summary: license components for the compat-libffi-soname6 package.
Group: Default

%description license
license components for the compat-libffi-soname6 package.


%prep
%setup -q -n libffi-3.2.1
cd %{_builddir}/libffi-3.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1616687100
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1616687100
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libffi-soname6
cp %{_builddir}/libffi-3.2.1/LICENSE %{buildroot}/usr/share/package-licenses/compat-libffi-soname6/0155a7d592674828653b18e044fe6ea2685fac13
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/lib64/libffi-3.2.1/include/ffi.h
rm -f %{buildroot}/usr/lib64/libffi-3.2.1/include/ffitarget.h
rm -f %{buildroot}/usr/lib64/libffi.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libffi.pc
rm -f %{buildroot}/usr/share/info/libffi.info
rm -f %{buildroot}/usr/share/man/man3/ffi.3
rm -f %{buildroot}/usr/share/man/man3/ffi_call.3
rm -f %{buildroot}/usr/share/man/man3/ffi_prep_cif.3
rm -f %{buildroot}/usr/share/man/man3/ffi_prep_cif_var.3

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libffi.so.6
/usr/lib64/libffi.so.6.0.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libffi-soname6/0155a7d592674828653b18e044fe6ea2685fac13
